### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by mfn003** [TwrpBuilder/android_device_samsung_j1pop3gjv#3]
Following the steps on the Travis CI YAML file will result in a not found error OR it'll give many errors with the minimal manifest TWRP branch.

New changes have been made about CPU temperature.

**Comment by berkantkz** [comment]
well, that doesn't seem to be an issue as you already made changes and sent pull request which was approved.

**Comment by mfn003** [comment]
I can't build TWRP with the steps given on the Travis CI YAML, and no automated builds are being made. The cleaned TWRP 5.1.1 repository is now gone, and I'm stuck on the minimal manifest provided by the recovery team. 

@berkantkz The changes might not be the issue, but the building is.
